# -*- coding: utf-8 -*-
"""visual.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/193F01sBeht-eh9OLczVYHx1VEidnY5gU
"""

import sklearn.datasets

for i in range(2,10):
  for j in range(1,10):
    print("%d * %d = %2d" %(i,j,i*j), end='\t')
  print("\n")

import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0,np.pi*4,0.01)
plt.plot(x, np.sin(x),label='sin')
plt.plot(x, np.cos(x),label='cos')
plt.legend(loc=0)
plt.show()

import random
balls = [i for i in range(1, 46)]
for i in range(6):
  print(random.choice(balls), end=' ')

import pandas as pd

chipo = pd.read_csv("chipotle.tsv.txt", sep="\t")

chipo

chipo.shape

chipo.info()

chipo.head(10)

chipo.columns

chipo.index

chipo.describe()

chipo["order_id"] = chipo["order_id"].astype(str)

chipo["order_id"].unique()
len(chipo["order_id"].unique())

chipo["item_name"].unique()

chipo["item_name"].value_counts()[:10]

chipo.groupby("item_name")["order_id"].count()

chipo.groupby("item_name")["quantity"].sum()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

item_quantity = chipo.groupby("item_name")["quantity"].sum()
item_name_list = item_quantity.index.tolist()
x_pos = np.arange(len(item_name_list))
order_cnt = item_quantity.values.tolist()

plt.bar(x_pos, order_cnt, align='center')
plt.ylabel("Ordered Item Count")
plt.title("Distribution of all ordered item")
plt.show()

chipo["item_price"] = chipo["item_price"].apply(
    lambda x: float(x[1:])
)

chipo.describe()

chipo.groupby("order_id")["item_price"].sum()

chipo.groupby("order_id")["item_price"].sum().mean()

chipo_order_id_group = chipo.groupby("order_id").sum()
chipo_order_id_group[chipo_order_id_group["item_price"] >= 10]

chipo_singular = chipo[chipo["quantity"] == 1]
chipo_singular

price_per_item = chipo_singular.groupby("item_name").min()
price_per_item

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
item_name_list = price_per_item.index.tolist()
x_pos = np.arange(len(item_name_list))
item_price = price_per_item["item_price"].tolist()

plt.bar(x_pos, item_price, align='center')
plt.ylabel("Item Price($)")
plt.title("Distribution of item price")
plt.show()

